name: Release and Build hla_la Docker image

on:
  workflow_dispatch:
    inputs:
      minor-release:
        description: "Is this a patch release?"
        type: boolean
        required: false
        default: false
      create-release:
        description: "Create a GitHub Release?"
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: write

jobs:
  release-and-build:
    uses: Ultimagen/ugbio-utils/.github/workflows/release-and-build-docker.yml@main
    secrets: inherit
    with:
      docker-image: hla_la
      minor-release: ${{ inputs.minor-release }}
      create-release: ${{ inputs.create-release }}
