name: Trivy scan
on:
  push:
    branches:
      - ug-master
  pull_request:
jobs:
  trivy-scan-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: './'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
